services:
  - type: web
    name: ozlotter-smartpro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10